server:
  port: 8001

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/remindee-auth
    password: root
  jpa:
    defer-datasource-initialization: always
    hibernate:
      ddl-auto: create-drop

remindee:
  client-id: client-id
  client-secret: s3cr3t
  refresh:
    token:
      validity:
        seconds: '3600'
  scopes: read,write
  check:
    token:
      access: isAuthenticated()
  token:
    key:
      access: permitAll()
  authorization:
    grant:
      types: password,refresh_token
  access:
    token:
      validity:
        seconds: '3600'

logging:
  level:
    org:
      springframework:
        security: DEBUG