server:
  port: 9999


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: remindee-users
          uri: lb://remindee-users
          predicates:
            - Path=/api/v1/users/**
