server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://remindee-authorization:8001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/remindee-users
    password: root
  jpa:
    defer-datasource-initialization: always
    hibernate:
      ddl-auto: update